from .characters import CHARS as CHARS
from _typeshed import Incomplete

__version__: str
char_names: Incomplete

class CowsayError(LookupError): ...

def wrap_lines(lines: list, max_width: int = ...) -> list: ...
def generate_bubble(text: str) -> list: ...
def generate_char(char_lines: str, text_width: int) -> list: ...
def draw(text: str, char_lines: str, to_console: bool = ...) -> str: ...
def get_output_string(char: str, text: str) -> str: ...
